[package]
name = "last-prove"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies.sdl2]
version = "*"
default-features = false
features = ["image", "ttf"]

[dependencies]
rand = "*"
